### ISSUE TITLE
Melhorar mensagem de erro quando não encontrar um handler

### ISSUE THREAD

**Issue by bernardo-bruning** [nepente/Cqs#2]
Bom, acredito que para algumas pessoas a mensagem não vem a ser muito "amigável", pois não indica que o dispatcher não conseguiu achar um handler para executar.

> An exception of type 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' occurred in System.Core.dll but was not handled in user code
> 
> Additional information: Não é possível fazer associação em tempo de execução em uma referência nula

**Comment by andrepoleza** [comment]
@bernardo-bruning, ficaria contente com um PR. O que achas?

**Comment by andrepoleza** [comment]
Feito. 🦄
