### ISSUE TITLE
Target .NETStandard

### ISSUE THREAD

**Issue by bernardo-bruning** [nepente/Cqs#4]

**Comment by diegobfernandez** [comment]
@bernardo-bruning comecei a trabalhar nisso e você pode acompanhar/colaborar no branch [feature/dotnetstandard](/nepente/CQS/tree/feature/dotnetstandard)

**Comment by diegobfernandez** [comment]
.NETStandard support was added on commit dd98f62.
It's available on version 1.0.0-beta1
